# Generated by Django 5.1.2 on 2024-10-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrochetapp', '0004_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Pattern Name'),
        ),
    ]
